--Review tables 

SELECT * FROM CUSTOMER_ORDER;

SELECT * FROM CUSTOMER;

---- Data Profiling Queries

-- 1. % NULL

SELECT count(1) FROM CUSTOMER_ORDER;

SELECT count(1) FROM CUSTOMER_ORDER WHERE CUSTOMER_ID IS NULL;

SELECT count(1) FROM CUSTOMER_ORDER WHERE CUSTOMER_PHONE IS NULL;

SELECT count(1) FROM CUSTOMER_ORDER WHERE ORDER_ID IS NULL;

SELECT count(1) FROM CUSTOMER_ORDER WHERE ORDER_DATE IS NULL;

SELECT count(1) FROM CUSTOMER_ORDER WHERE SALE_AMOUNT IS NULL;


-- 2. Minimum and Maximum

SELECT MIN(ORDER_DATE),MAX(ORDER_DATE)  FROM CUSTOMER_ORDER ;

-- 3. Range profiling 

SELECT * FROM ORDER_SALE_AMOUNT_GROUP;

SELECT SALE_AMOUNT_GROUP "Sale Amount Group",COUNT(1) "Record Count" FROM ORDER_SALE_AMOUNT_GROUP
GROUP BY SALE_AMOUNT_GROUP
ORDER BY SALE_AMOUNT_GROUP;

SELECT * FROM CUSTOMER_ORDER WHERE SALE_AMOUNT>150;


-- Data Quality Dimension Queries

--Review tables 

SELECT * FROM CUSTOMER_ORDER;

SELECT * FROM CUSTOMER;

-- 1. Consistency 

SELECT DISTINCT 
    ORDR.CUSTOMER_ID "Customer ID",
    CUST.FIRST_NAME||' '||CUST.LAST_NAME "Customer Name",
    ORDR.CUSTOMER_PHONE "Customer Phone On Order Table",
    CUST.PHONE_NUMBER "Customer Phone On Customer Table"
FROM CUSTOMER_ORDER ORDR 
JOIN CUSTOMER CUST 
ON ORDR.CUSTOMER_ID = CUST.CUSTOMER_ID;

-- 2. Uniqueness

SELECT * FROM CUSTOMER;